### ISSUE TITLE
LUNC payment gateway

### ISSUE THREAD

**Issue by mehranrezaei** [terra-rebels/terra-sharp#2]
I am working in a software development team that is implementing a very large project similar to Udemy. We plan to accept LUNC as a payment method.
Can anyone advise where I should start to implement this payment method?
Our development technology is ASP.NET with C#. 

I found this project but it seems incomplete and non-functional. I am looking for a library for C#.

**Comment by TheArchitect123** [comment]
Hi There,

This project is still in development.
For now we only have a typescript and python implementation for LUNC.

Please use this library here for now.
https://github.com/terra-rebels/terra.js

**Comment by TheArchitect123** [comment]
Hey mate,

If you're still looking to integrate payments for LUNC/LUNA.

Please use this library here:
https://github.com/TerraMystics/Terra.Net.OnChainPayments
